# Generated by Django 3.1.12 on 2021-06-03 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
