# Generated by Django 3.1.12 on 2021-06-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktrip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='venue_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
