# Generated by Django 3.1.12 on 2021-06-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktrip', '0002_location_venue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='download_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='upload_speed',
            field=models.IntegerField(default=0),
        ),
    ]
